### PR TITLE
re-start in this new repository

### PR DESCRIPTION
**Pull request by SevlaMare**
-Move to this new repository to work in same branch.
-Finish basic structure of index.html and style.css
-Fixed margins and padding.
-Match typography and colors contrast
-Added generic font family.
-Fixed Linter and validador issues.

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: amazing!

Here are things you need to change before this project can be approved:
* [x] Change name of project in README file, right now it says "Apple clone" .

##### Navigation bar
* [x] It  should use `div` and positions elements as at the source page (content is not important) ([link to page](https://www.smashingmagazine.com/))

##### Main content
* [x] `banner-systems` div should be an article
* [x] `author` div should be an article
* [x] `banner-green` div should be an article
* [x] `box-12` div should be an article
* [x] `hero-1` div should be an article

##### Footer
* [x] It should contain centered links (content is not important) ([link to page](https://www.smashingmagazine.com/)).

**Comment by paulgureghian** [comment]
Here are things you need to change before this project can be approved:

Change name of project in README file, right now it says "Apple clone" .
Solution: I improved the README.md file.

Main content
 banner-systems div should be an article
 author div should be an article
 banner-green div should be an article
 box-12 div should be an article
 hero-1 div should be an article
Solution: I changed the 'div' tags to 'article' tags. the validator faulted 
on of the changes, I had to change a 'p' tag to a 'h4' tag. 

Navigation bar
 It should use div and positions elements as at the source page (content is not important) (link to page)
Solution: I am not sure what this means exactly. my code does use 'div' tags as well a 'nav' tag just like the original page. I need to change the 'nav' tag to a 'div' tag ? and the positioning looks good. 

Footer
 It should contain centered links (content is not important) (link to page).
Solution: The links look centered. exactly what needs to be fixed here ? 

Thanks.

**Comment by pelzolga123** [comment]
1. On original website navbar is inside div. Navbar contains only 5 menu buttons. Topic button is outside navbar, aligned with it inside said div. Inspect original website and you will understand it better. 
2. You don't have links, just `li` tags.

**Review by rOluochKe — APPROVED** [review]
Hello Team,

### Good job :clap: Having seen you have worked on the recommended changes from the previous reviews. Your project looks good and I, therefore, approve of it.  Congratulations :boom: :100:
### You can merge to master and submit a project completion form from your dashboard. Good luck with the next project.
- Happy coding!

**Pull request merged**
